---
title: "Sanity Checks"
author: "Kristian Severin"
date: "10/27/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("rmarkdown")

#Loading packages

pacman::p_load(tidyverse, lmerTest, lme4, rstatix, tidyr, zoo, ggpubr, gridExtra, interactions, car, lmtest)

```


```{r}

#loading data

data <- read_csv("all_data-1.csv")

#Removing Na's
data_clean<-data[!(data$picked_low_LH=="NaN"),]

#cleaning environment and loading clean data as "data"
data <- read_csv("data_clean.csv")

```



```{r}
#Making longer by eta
data_log1 = data %>% pivot_longer(., c(model_parameter_eta_LH, model_parameter_eta_SH), names_to = "Novelty_bonus") 

#Making longer by sigma
data_log2 = data %>% pivot_longer(., c(model_parameter_sgm0_LH, model_parameter_sgm0_SH), names_to = "Prior_variance") 

#Making longer by xi

data_log3 = data %>% pivot_longer(., c(model_parameter_xi_LH, model_parameter_xi_SH), names_to = "Information_bonus")



```






Data transformation chunk
```{r}

#Gender as factor
data_log1$gender <- as.factor(data_log1$gender)

data_log2$gender <- as.factor(data_log2$gender)

data_log3$gender <- as.factor(data_log3$gender)



#Model parameters as factor
data_log1$Novelty_bonus <- as.factor(data_log1$Novelty_bonus)

data_log2$Prior_variance <- as.factor(data_log2$Prior_variance)

data_log3$Information_bonus <- as.factor(data_log3$Information_bonus)




#Filtering category 3
data_log1 = data_log1%>% subset(.$gender != "3")

data_log2 = data_log2%>% subset(.$gender != "3")

data_log3 = data_log3%>% subset(.$gender != "3")

data = data %>% subset(.$gender != "3")

```





```{r visualizations}

#Visualizations 

p1 <- ggline(
  data = data_log1,
  x = "gender",
  y = "value",
  col = "Novelty_bonus", 
  add = "mean_se",
  )+
   ggtitle("Gender Effects")+
  theme_cleveland()


p2 <- ggline(
  data = data_log1,
  x = "age",
  y = "value",
  col = "Novelty_bonus", 
  add = "mean_se",
  )+
  ggtitle("Age Effects")+
  theme_cleveland()


p3 <- ggline(
  data = data_log2,
  x = "gender",
  y = "value",
  col = "Prior_variance", 
  add = "mean_se",
  )+
   ggtitle("Gender Effects")+
  theme_cleveland()


p4 <- ggline(
  data = data_log2,
  x = "age",
  y = "value",
  col = "Prior_variance", 
  add = "mean_se",
  )+
  ggtitle("Age Effects")+
  theme_cleveland()



p5 <- ggline(
  data = data_log3,
  x = "gender",
  y = "value",
  col = "Information_bonus", 
  add = "mean_se",
  )+
   ggtitle("Gender Effects")+
  theme_cleveland()


p6 <- ggline(
  data = data_log3,
  x = "age",
  y = "value",
  col = "Information_bonus", 
  add = "mean_se",
  )+
  ggtitle("Age Effects")+
  theme_cleveland()




p8 <- ggline(
  data = data,
  x = "age",
  y = "model_parameter_Q0",
  col = "gender", 
  add = "mean_se",
  )+
  ggtitle("A: Age Effects & Gender Effects")+
  theme_cleveland()





pa1 <- grid.arrange(p1, p2)

pa2 <- grid.arrange(p3,p4)

pa3 <- grid.arrange(p5,p6)

p4 <- grid.arrange(p8, lm4.2)





```


```{r Novelty Bonus Models}


#----------------------------------------#Novelty Bonus models#--------------------------------------------#

data_log1.1 <- mutate_if(data_log1, is.numeric, log2)
data_log1.2 <- mutate_if(data_log1, is.numeric, sqrt)



#lm Novelty_bonus
lm1 <- lm (data = data_log1, value ~ 0 + Novelty_bonus*gender + Novelty_bonus*age + age*gender) 
summary(lm1)

#log_scaled
lm1.log <- lm (data = data_log1.1, value ~ 0 + Novelty_bonus*gender + Novelty_bonus*age + age*gender) 
summary(lm1.log)


#lm Novelty_bonus with intercept
lm1.1 <- lm (data = data_log1, value ~ Novelty_bonus*gender + Novelty_bonus*age + age*gender) 
summary(lm1.1)

#lm Novelty_bonus with intercept log scaled
lm1.1.log <- lm (data = data_log1.1, value ~ Novelty_bonus*gender + Novelty_bonus*age + age*gender) 
summary(lm1.1.log)


#lm Novelty_bonus with intercept and three-way interactions
lm1.1.1 <- lm (data = data_log1, value ~ Novelty_bonus*gender + Novelty_bonus*age + age*gender + age*gender*Novelty_bonus) 
summary(lm1.1.1)

#lm Novelty_bonus with intercept and three-way interactions log scaled
lm1.1.1.log <- lm (data = data_log1.1, value ~ Novelty_bonus*gender + Novelty_bonus*age + age*gender + age*gender*Novelty_bonus) 
summary(lm1.1.1.log)





model1 <- lm(data = data_log1.2, value ~ gender*age )
summary(model1)
```


```{r assumption checks for LM Novelty Bonus}


#Residual vs fitted plot
plot(lm1.1.1, 1)

#qq-plot
plot(lm1.1.1, 2)

#Scale-location plot
plot(lm1.1.1, 3)

## non-constant error variance test because in doubt
ncvTest(lm1.1.1)

#Histogram of residuals
hist(lm1.1.1$residuals)

plot(lm1.1.1, 4)


plot(lm1.1.1, 5)







```




```{r Prior Variance Models}


#--------------------------------------#Prior Variance models#-----------------------------------------------#

data_log2.2 <- mutate_if(data_log2, is.numeric, sqrt)

data_log2.1[,104] <- log(data_log2[104],2)

data_log2.1$logweight=log(data_log2.1$value)

data_log2.1$logweight <- na.omit(data_log2.1$logweight)

outlierTest(lm2.1.1)

lm2.1.2 <- lm2.1.1$residuals[]


#lm Prior_variance
lm2 <- lm (data = data_log2, value ~ 0 + Prior_variance*gender + Prior_variance*age + age*gender) 
summary(lm2)

#lm Prior_variance with intercept
lm2.1 <- lm (data = data_log2, value ~ Prior_variance*gender + Prior_variance*age + age*gender) 
summary(lm2.1)

#lm Prior_variance with intercept log scaled
lm2.1 <- lm (data = data_log2.1, value ~ Prior_variance*gender + Prior_variance*age + age*gender) 
summary(lm2.1)


#lm Prior_variance with intercept and three-way interaction
lm2.1.1 <- lm (data = data_log2, value ~ Prior_variance*gender + Prior_variance*age + age*gender + age*gender*Prior_variance) 
summary(lm2.1.1)

#lm Prior_variance with intercept log scaled and three-way interaction
lm2.1 <- lm (data = data_log2.1, value ~ Prior_variance*gender*age) 
summary(lm2.1)



#lm Prior_variance with intercept log scaled (all) and three-way interaction
lm2.2 <- lm (data = data_log2.1, logweight ~ age*gender*Prior_variance) 
summary(lm2.2) 


model2 <- lm(data = data_log2.2, value ~ gender*age)
summary(model2)
```


```{r assumption checks Prior Variance model}


#Residual vs fitted plot
plot(lm2.1, 1)

#Durbin Watson Test
durbinWatsonTest(lm2.1, lag = 2)

dwtest(lm2.1, iterations = 100)

?dwtest

#Scale-location plot
plot(lm2.1, 3)

## non-constant error variance test because in doubt
ncvTest(lm2.1)

#Histogram of residuals
hist(lm2.1$residuals)

#qq
plot(lm2.1, 2)


hist(data_log2$value)

?ncvTest

```



```{r prior_variance without horizon}

mod1 <- lm(data = data_log1, value ~ age)
summary(mod1)

mod2 <- lm(data = data_log2, value ~ age)
summary(mod2)

mod3 <- lm(data = data_log3, value ~ age)
summary(mod3)




```



```{r belief about reward models}
#---------------------------------------#Belief about reward Models#-------------------------------------------------#

#lm Prior_variance with intercept
lm4.1 <- lm (data = data, model_parameter_Q0 ~ age*gender) 
summary(lm4.1)

#---------------------------------------#And Assumption checks#-------------------------------------------------#


#Residual vs fitted plot
plot(lm4.1, 1)

#Durbin Watson Test
durbinWatsonTest(lm4.1)

dwtest(lm4.1)

#Scale-location plot
plot(lm4.1, 3)

## non-constant error variance test because in doubt
ncvTest(lm4.1)

#Histogram of residuals
hist(lm4.1$residuals)

#qq
plot(lm4.1, 2)





```






```{r Information Bonus Models}
#---------------------------------------#Information Bonus Models#-------------------------------------------------#

data_log3.2 <- mutate_if(data_log3, is.numeric, log2)


#lm Information_bonus
lm3 <- lm (data = data_log3, value ~ 0 + Information_bonus*gender + Information_bonus*age + age*gender) 
summary(lm3)

#lm Information_bonus with intercept
lm3.1 <- lm (data = data_log3, value ~ Information_bonus*gender + Information_bonus*age + age*gender) 
summary(lm3.1)

#lm Information_bonus with intercept and three-way interaction
lm3.1.1 <- lm (data = data_log3, value ~ Information_bonus*gender*age) 
summary(lm3.1.1)




```




```{r assumption checks Information Bonus model}

#Residual vs fitted plot
plot(lm3.1, 1)

#Durbin Watson Test
durbinWatsonTest(lm3.1)


#Scale-location plot
plot(lm3.1, 3)

## non-constant error variance test because in doubt
ncvTest(lm3.1)

#Histogram of residuals
hist(lm3.1$residuals)


plot(lm3.1, 2)

```






```{r Novelty Bonus Interactions}


#No intercept model Novelty bonus
lm1c <- cat_plot(lm1,  pred = "gender", modx = "Novelty_bonus", plot.points = T)

lm1i <- interact_plot(lm1,  pred = "age", modx = "Novelty_bonus", plot.points = T)


#Intercept model Novelty bonus
lm1.1c <- cat_plot(lm1.1, pred = "gender", modx = "Novelty_bonus", plot.points = F)

lm1.1i <- interact_plot(lm1.1, pred = "age", modx = "Novelty_bonus", plot.points = F)

lm1log <- cat_plot(lm1.1.log, pred = "age", modx = "Novelty_bonus", plot.points = F)

#All Novelty bonus models
grid.arrange(lm1c, lm1i)





```



```{r Prior Variance Interactions}

#No intercept model Prior variance
lm2c <- cat_plot(lm2,  pred = "gender", modx = "Prior_variance", plot.points = T)

lm2i <- interact_plot(lm2,  pred = "age", modx = "Prior_variance", plot.points = T)



#Intercept model Prior variance
lm2.1c <- cat_plot(lm2.1, pred = "gender", modx = "Prior_variance", plot.points = F)

lm2.1i <- interact_plot(lm2.1, pred = "age", modx = "Prior_variance", plot.points = F)


#Intercept and sqrt transformed interactions
lm2.2i <- interact_plot(lm2.2,  pred = "age", modx = "Prior_variance", plot.points = T)

lm2.2c <- cat_plot(lm2.2,  pred = "gender", modx = "Prior_variance", plot.points = T)

lmint <-  cat_plot(lm2.1,  pred = "gender", modx = "Prior_variance", mod2 = "age", plot.points = T)

lmint

lm2.2c



#All Prior variance models
grid.arrange(lm2c, lm2i)

data$gender <- as.factor(data$gender)


```




```{r Information Bonus Interactions}


#No intercept model Information bonus
lm3c <- cat_plot(lm3,  pred = "gender", modx = "Information_bonus", plot.points = T)

lm3i <- interact_plot(lm3,  pred = "age", modx = "Information_bonus", plot.points = T)


#Intercept model Information bonus 
lm3.1c <- cat_plot(lm3.1, pred = "gender", modx = "Information_bonus", plot.points = F)

lm3.1i <- interact_plot(lm3.1, pred = "age", modx = "Information_bonus", plot.points = F)

#All Prior Information bonus
grid.arrange(lm3c, lm3i)


```


```{r belief parameter interaction}

lm4.2 <- interact_plot(lm4.1, pred = "age", modx = "gender", plot.points = T)+
  ggtitle("B: Age-by-Gender Interaction")
lm4.2

```






